[dependencies]
ratatui = "0.26"
crossterm = "0.27"
chrono = "0.4"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
notify-rust = "4.8.0"
tokio = { version = "1", features = ["full"] }

